### PR TITLE
update json library versions

### PR DESCRIPTION
**Pull request by SentryMan**

### CODE REVIEW

**Review by fabienrenaud — CHANGES_REQUESTED** [review]
fastjson's latest version is 2.0.26.
Could you also double check the other ones please in maven central?
Thank you for the support! :)

**Comment by SentryMan** [comment]
also yasson uses jakarta instead of javax now, so will have to untangle that mess

**Comment by SentryMan** [comment]
I can't upgrade yasson because apache johnzon is using javax JSONP.

**Comment by SentryMan** [comment]
other than yasson that's all of them

**Comment by SentryMan** [comment]
@rmannibucau, I see you are involved with johnzon, do you know when/if they will use jakarta JSON-P?

**Comment by rmannibucau** [comment]
@SentryMan not sure what you mean, johnzon implements and uses JSON-P in its mapper and JSON-B implementations since day one and provides a jakarta flavor since a few versions (but can need to play with classifier until next release - try `io.yupiik.uship:backbone-johnzon:1.0.16:pom` as a presetup pom).

**Comment by SentryMan** [comment]
> but can need to play with classifier until next release

you really do learn something new every day, I never encountered maven classifiers until now.

In any case, we're good now

**Review by fabienrenaud — APPROVED** [review]
Great! Thank you!

**Comment by fabienrenaud** [comment]
I ran and published new benchmark results today. Thanks again @SentryMan This contribution and the others you did definitely helped me fast-tracking running it.

**Pull request merged**
