### PR TITLE
Remove Jsoniter

### PR DESCRIPTION
**Pull request by SentryMan**
I guess it's not working on JDK 17.

### CODE REVIEW

**Comment by fabienrenaud** [comment]
Flagged the issue on the java jsoniter project: https://github.com/json-iterator/java/issues/341

**Comment by plokhotnyuk** [comment]
@fabienrenaud @SentryMan How about using [jsoniter-scala](https://github.com/plokhotnyuk/jsoniter-scala)?

Would you allow to the Scala beast to beat all Java kittens?

**Comment by SentryMan** [comment]
You could probably raise a pr to add if you want.

> Would you let the beast of Scala beat all the Java kittens?

Oho? I'd like to see you try at least.

**Comment by fabienrenaud** [comment]
@plokhotnyuk I don't mind as long as it integrates well into the project (I don't see how since everything is written in Java). Feel free to send a PR though.

**Comment by plokhotnyuk** [comment]
> @plokhotnyuk I don't mind as long as it integrates well into the project (I don't see how since everything is written in Java). Feel free to send a PR though.

Yep, before doing that I would refactor your benchmark to be simpler, correct, and more reusable.

Please see how benchmarks are implemented to test different JSON parsers for Scala on different platforms [here](https://github.com/plokhotnyuk/jsoniter-scala/tree/master/jsoniter-scala-benchmark).

**Comment by fabienrenaud** [comment]
> before doing that I would refactor your benchmark to be simpler, correct, and more reusable.

@plokhotnyuk Sounds great!
What do you find to be _not_ correct with this benchmark?

**Pull request merged**
