### PR TITLE
Add benchmarking for mjson.

### PR DESCRIPTION
**Pull request by brcolow**
Adds support for the [mjson](https://github.com/bolerio/mjson) library.

I think what I have here is correct, not 100% confident as I didn't actually generate the benchmark results yet. Hoping you can easily test what's there and make sure it is kosher.

Thanks very much.

### CODE REVIEW

**Comment by fabienrenaud** [comment]
Looks good.
Does mjson support reading from InputStream and writing to OutputStream? Or bytes? String is the most inefficient way of parsing and writing... No support for databinding I suppose?

Can you run the benchmark at least once and publish the results here? Using the run command against mjson and jackson only would be enough.

**Comment by brcolow** [comment]
From what I can tell mjson can only read Strings and CharacterIterators. I am not sure if the `Json.make` method qualifies as databinding. I will try and run the benchmarks and LYK. I figured you would re-run them if this is merged.

**Comment by brcolow** [comment]
I added a new commit that adds a Windows powershell equivalent script for `run`. It can be called thusly:

`.\run.ps1 ser --apis stream --libs "jackson,mjson"`

Note the double quotes around the `--libs` argument, these are necessary for it to work.

It's a bit hacky because passing the arguments through was not trivial.

Anyways, here's the results:

```
# JMH version: 1.20
# VM version: JDK 10.0.1, VM 10.0.1+10
# VM invoker: C:\Program Files\Java\jre-10.0.1\bin\java.exe
# VM options: <none>
# Warmup: 5 iterations, 1 s each
# Measurement: 10 iterations, 3 s each
# Timeout: 10 min per iteration
# Threads: 16 threads, will synchronize iterations
# Benchmark mode: Throughput, ops/time
# Benchmark: com.github.fabienrenaud.jjb.stream.Serialization.jackson

# Run progress: 0.00% complete, ETA 00:02:20
# Fork: 1 of 2
# Warmup Iteration   1: Using SEED=708125664 as seed for Random
611363.643 ops/s
# Warmup Iteration   2: 832637.917 ops/s
# Warmup Iteration   3: 860103.662 ops/s
# Warmup Iteration   4: 851752.158 ops/s
# Warmup Iteration   5: 853688.714 ops/s
Iteration   1: 853394.779 ops/s
Iteration   2: 854234.988 ops/s
Iteration   3: 859962.741 ops/s
Iteration   4: 850037.902 ops/s
Iteration   5: 844487.316 ops/s
Iteration   6: 842050.965 ops/s
Iteration   7: 839580.005 ops/s
Iteration   8: 836353.430 ops/s
Iteration   9: 840451.297 ops/s
Iteration  10: 821805.944 ops/s

# Run progress: 25.00% complete, ETA 00:01:55
# Fork: 2 of 2
# Warmup Iteration   1: Using SEED=708125664 as seed for Random
585427.077 ops/s
# Warmup Iteration   2: 808400.644 ops/s
# Warmup Iteration   3: 845703.097 ops/s
# Warmup Iteration   4: 868075.436 ops/s
# Warmup Iteration   5: 864514.517 ops/s
Iteration   1: 844864.386 ops/s
Iteration   2: 869260.261 ops/s
Iteration   3: 877645.529 ops/s
Iteration   4: 874597.528 ops/s
Iteration   5: 833487.701 ops/s
Iteration   6: 834658.178 ops/s
Iteration   7: 765367.861 ops/s
Iteration   8: 715914.939 ops/s
Iteration   9: 718233.594 ops/s
Iteration  10: 687015.645 ops/s


Result "com.github.fabienrenaud.jjb.stream.Serialization.jackson":
  823170.249 ±(99.9%) 48121.269 ops/s [Average]
  (min, avg, max) = (687015.645, 823170.249, 877645.529), stdev = 55416.525
  CI (99.9%): [775048.981, 871291.518] (assumes normal distribution)


# JMH version: 1.20
# VM version: JDK 10.0.1, VM 10.0.1+10
# VM invoker: C:\Program Files\Java\jre-10.0.1\bin\java.exe
# VM options: <none>
# Warmup: 5 iterations, 1 s each
# Measurement: 10 iterations, 3 s each
# Timeout: 10 min per iteration
# Threads: 16 threads, will synchronize iterations
# Benchmark mode: Throughput, ops/time
# Benchmark: com.github.fabienrenaud.jjb.stream.Serialization.mjson

# Run progress: 50.00% complete, ETA 00:01:16
# Fork: 1 of 2
# Warmup Iteration   1: Using SEED=708125664 as seed for Random
36347.767 ops/s
# Warmup Iteration   2: 104946.091 ops/s
# Warmup Iteration   3: 137770.813 ops/s
# Warmup Iteration   4: 144467.656 ops/s
# Warmup Iteration   5: 151477.301 ops/s
Iteration   1: 157705.717 ops/s
Iteration   2: 157074.994 ops/s
Iteration   3: 148033.506 ops/s
Iteration   4: 151354.044 ops/s
Iteration   5: 169342.736 ops/s
Iteration   6: 176147.917 ops/s
Iteration   7: 177369.793 ops/s
Iteration   8: 180168.841 ops/s
Iteration   9: 179741.463 ops/s
Iteration  10: 179394.410 ops/s

# Run progress: 75.00% complete, ETA 00:00:38
# Fork: 2 of 2
# Warmup Iteration   1: Using SEED=708125664 as seed for Random
45817.746 ops/s
# Warmup Iteration   2: 134165.678 ops/s
# Warmup Iteration   3: 167990.669 ops/s
# Warmup Iteration   4: 171892.158 ops/s
# Warmup Iteration   5: 175626.754 ops/s
Iteration   1: 174050.436 ops/s
Iteration   2: 173488.159 ops/s
Iteration   3: 173692.732 ops/s
Iteration   4: 174794.873 ops/s
Iteration   5: 174431.709 ops/s
Iteration   6: 173290.687 ops/s
Iteration   7: 162846.322 ops/s
Iteration   8: 171490.012 ops/s
Iteration   9: 174464.438 ops/s
Iteration  10: 168794.769 ops/s


Result "com.github.fabienrenaud.jjb.stream.Serialization.mjson":
  169883.878 ±(99.9%) 8208.221 ops/s [Average]
  (min, avg, max) = (148033.506, 169883.878, 180168.841), stdev = 9452.600
  CI (99.9%): [161675.657, 178092.099] (assumes normal distribution)


# Run complete. Total time: 00:02:34

Benchmark               Mode  Cnt       Score       Error  Units
Serialization.jackson  thrpt   20  823170.249 ± 48121.269  ops/s
Serialization.mjson    thrpt   20  169883.878 ±  8208.221  ops/s
```

**Comment by fabienrenaud** [comment]
> I am on Windows so I can't use the run script without launching a VM, I can do that tomorrow, though.

You should set yourself up with vagrant. You'll get a working linux terminal in minutes without effort. :)

I will verify it this week-end and merge if everything is alright.
Considering the performance of mjson isn't exactly terrific (5x worse than json puts it close to gson), I'll hold off onto running the whole benchmark suite for a while and wait for a better opportunity (I updated all results less than a month ago).

**Comment by fabienrenaud** [comment]
Results for serialization and deserialization:

```
> ./run deser --apis stream --libs orgjson,mjson,gson,jackson
Benchmark                 Mode  Cnt       Score       Error  Units
Deserialization.orgjson  thrpt   20  169261.387 ±  2029.437  ops/s
Deserialization.mjson    thrpt   20  277424.958 ± 17916.256  ops/s
Deserialization.gson     thrpt   20  475831.499 ± 27827.967  ops/s
Deserialization.jackson  thrpt   20  785321.118 ± 22076.430  ops/s
```
```
> ./run ser --apis stream --libs orgjson,mjson,gson,jackson
Benchmark               Mode  Cnt        Score       Error  Units
Serialization.mjson    thrpt   20   163690.878 ±  9799.682  ops/s
Serialization.orgjson  thrpt   20   171544.708 ±  1447.284  ops/s
Serialization.gson     thrpt   20   245972.292 ±  7951.121  ops/s
Serialization.jackson  thrpt   20  1416175.410 ± 27383.310  ops/s
```

**Pull request merged**
