### PR TITLE
use javax.json streaming

### PR DESCRIPTION
**Pull request by tbutter**
Use the streaming version of the javax.json api to be comparable with the other streaming implementations.

### CODE REVIEW

**Comment by fabienrenaud** [comment]
1k serialization bench
```
> ./run ser --number 1 --size 1 --libs javaxjson,jackson --apis stream

Benchmark                                            Mode  Cnt        Score       Error  Units
c.g.f.j.stream.Serialization.jackson                thrpt   20  1313636.065 ± 94808.818  ops/s
c.g.f.j.stream.Serialization.javaxjson              thrpt   20    42442.679 ±  1822.025  ops/s
```

10kb deserialization bench
```
> ./run deser --number 1 --size 10 --libs javaxjson,jackson --apis stream
Benchmark                   Mode  Cnt       Score      Error  Units
Deserialization.jackson    thrpt   20  159284.778 ± 5469.069  ops/s
Deserialization.javaxjson  thrpt   20   33865.047 ±  529.688  ops/s
```

Seems to be about the same perf as before.

Merging.
Thank you for your contribution.

**Comment by tbutter** [comment]
@fabienrenaud I was a 10x increase on my computer. (./run ser --libs javaxjson,jackson --apis stream did go from about 4k to 43k ops/s)

**Comment by fabienrenaud** [comment]
@tbutter Can you post your results here before/after the change (with a benchmark of some other lib – like jackson – as a baseline for comp)?

**Comment by tbutter** [comment]
Before:

Benchmark                                            Mode  Cnt        Score       Error  Units
c.g.f.j.databind.Serialization.jackson              thrpt   20  1128372,325 ± 68940,272  ops/s
c.g.f.j.databind.Serialization.jackson_afterburner  thrpt   20  1145477,484 ± 89842,216  ops/s
c.g.f.j.stream.Serialization.jackson                thrpt   20  1183593,001 ± 71676,136  ops/s
c.g.f.j.stream.Serialization.javaxjson              thrpt   20     4884,346 ±   403,721  ops/s

After:

Result "com.github.fabienrenaud.jjb.stream.Serialization.javaxjson":
  50201,844 ±(99.9%) 1661,622 ops/s [Average]
  (min, avg, max) = (43844,098, 50201,844, 52512,946), stdev = 1913,526
  CI (99.9%): [48540,222, 51863,466] (assumes normal distribution)


# Run complete. Total time: 00:02:52


Benchmark                 Mode  Cnt      Score      Error  Units
Serialization.javaxjson  thrpt   20  50201,844 ± 1661,622  ops/s

**Pull request merged**
